title: Oh sheep Im getting ruuum
author: Dima
email: dont write me
description: > # this means to ignore newlines until "baseurl:"
  Awesome.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
